version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lucky-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - lucky-network
    depends_on:
      - postgres
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=lucky_db
      - DB_USERNAME=lucky_user
      - DB_PASSWORD=lucky_password

  nginx:
    image: nginx:alpine
    container_name: lucky-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lucky-network
    depends_on:
      - app

  postgres:
    image: postgres:15-alpine
    container_name: lucky-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lucky_db
      POSTGRES_USER: lucky_user
      POSTGRES_PASSWORD: lucky_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lucky-network

volumes:
  postgres_data:
    driver: local

networks:
  lucky-network:
    driver: bridge
